use std::ops::{Deref, DerefMut};

use semigroup_derive::{OpPriv, properties_priv};

use crate::{Idempotent, Selected, Semigroup};

/// Some [`Semigroup`] such as [`crate::op::Coalesce`] can have an annotation.
///
/// A blanket implementation is provided for every [`Idempotent`] type, so any type that
/// implements [`Idempotent`] automatically gains the `.annotated(annotation)` method.
///
/// # Examples
/// ```
/// use semigroup::{op::Coalesce, Annotate, Annotated};
///
/// let annotated = Coalesce(Some(1)).annotated("first");
///
/// assert_eq!(annotated.value(), &Coalesce(Some(1)));
/// assert_eq!(annotated.annotation(), &"first");
/// assert_eq!(annotated, Annotated::new(Coalesce(Some(1)), "first"));
/// ```
pub trait Annotate<A>: Sized {
    fn annotated(self, annotation: A) -> Annotated<Self, A>;
}
impl<T: Idempotent, A> Annotate<A> for T {
    fn annotated(self, annotation: A) -> Annotated<Self, A> {
        Annotated::new(self, annotation)
    }
}

/// Trait for structs that have a per-field annotated form generated by
/// `#[derive(Semigroup)]` with `#[semigroup(annotated)]`.
///
/// # Examples
/// ```
/// use semigroup::{Annotate, AnnotateFields, Annotated, Semigroup};
///
/// #[derive(Debug, Clone, PartialEq, Semigroup)]
/// #[semigroup(annotated, with = "semigroup::op::Coalesce")]
/// struct Config {
///     num: Option<u32>,
///     #[semigroup(with = "semigroup::op::Overwrite")]
///     name: String,
/// }
///
/// let a = Config { num: Some(1), name: "a".into() }.annotated("cli");
/// let b = Config { num: None,    name: "b".into() }.annotated("file");
/// let ab = a.semigroup(b);
/// assert_eq!(ab.num.value(), &Some(1u32));
/// assert_eq!(ab.num.annotation(), &"cli");
/// assert_eq!(ab.name.value(), &"b".to_string());
/// assert_eq!(ab.name.annotation(), &"file");
/// ```
pub trait AnnotateFields<A>: Sized {
    type Annotated: Into<Self>;
    fn annotated(self, annotation: A) -> Self::Annotated;
}

/// [`Annotated`] wraps a value together with an annotation.
///
/// When `T` implements [`Idempotent`], `Annotated<T, A>` implements [`Semigroup`]:
/// the annotation always follows the selected operand.
///
/// # Properties
/// <!-- properties -->
///
/// # Examples
/// ```
/// use semigroup::{op::Coalesce, Annotate, Annotated};
///
/// let annotated = Coalesce(Some(1)).annotated("first");
///
/// assert_eq!(annotated.value(), &Coalesce(Some(1)));
/// assert_eq!(annotated.annotation(), &"first");
/// assert_eq!(annotated, Annotated::new(Coalesce(Some(1)), "first"));
/// ```
///
/// Duplicate annotation is not allowed:
/// ```compile_fail
/// use semigroup::{op::Coalesce, Annotate, Annotated};
///
/// let annotated = Coalesce(Some(1)).annotated("first").annotated("second");
/// assert_eq!(annotated.value().value(), &Coalesce(Some(1)));
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Default, Hash, OpPriv)]
#[op(
    commutative,
    commutative_where = "T: crate::Idempotent + crate::Commutative",
    hidden_inner
)]
#[properties_priv(
    commutative,
    commutative_where = "T: crate::Idempotent + crate::Commutative"
)]
pub struct Annotated<T, A> {
    value: T,
    annotation: A,
}
impl<T: Semigroup + Idempotent, A> Semigroup for Annotated<T, A> {
    fn op_assign(base: &mut Self, other: Self) {
        let selected = Idempotent::select(&base.value, &other.value);
        let (other_value, other_annotation) = other.into_parts();
        Semigroup::op_assign(&mut base.value, other_value);
        if let Selected::Other = selected {
            base.annotation = other_annotation;
        }
    }
}
// do not impl Annotated<T, A>: Annotate<A>
// impl<T: Idempotent, A> Idempotent for Annotated<T, A> {
//     fn select(base: &Self, other: &Self) -> Selected {
//         Idempotent::select(&base.value, &other.value)
//     }
// }

impl<T, A> Annotated<T, A> {
    /// [`Annotated`] has `new` method, but [`Annotated`] should be created by [`Annotate`] trait.
    pub fn new(value: T, annotation: A) -> Self {
        Self { value, annotation }
    }
    pub fn into_parts(self) -> (T, A) {
        (self.value, self.annotation)
    }
    pub fn parts(&self) -> (&T, &A) {
        (&self.value, &self.annotation)
    }
    pub fn into_value(self) -> T {
        self.value
    }
    pub fn value(&self) -> &T {
        &self.value
    }
    pub fn value_mut(&mut self) -> &mut T {
        &mut self.value
    }
    pub fn into_annotation(self) -> A {
        self.annotation
    }
    pub fn annotation(&self) -> &A {
        &self.annotation
    }
    pub fn annotation_mut(&mut self) -> &mut A {
        &mut self.annotation
    }

    pub fn map<U>(self, f: impl FnOnce(T) -> U) -> Annotated<U, A> {
        Annotated {
            value: f(self.value),
            annotation: self.annotation,
        }
    }
    pub fn map_annotation<B>(self, f: impl FnOnce(A) -> B) -> Annotated<T, B> {
        Annotated {
            value: self.value,
            annotation: f(self.annotation),
        }
    }
    pub fn map_parts<U, B>(
        self,
        fv: impl FnOnce(T) -> U,
        fa: impl FnOnce(A) -> B,
    ) -> Annotated<U, B> {
        Annotated {
            value: fv(self.value),
            annotation: fa(self.annotation),
        }
    }

    pub fn as_ref(&self) -> Annotated<&T, &A> {
        Annotated {
            value: &self.value,
            annotation: &self.annotation,
        }
    }
    pub fn as_ref_mut(&mut self) -> Annotated<&mut T, &A> {
        Annotated {
            value: &mut self.value,
            annotation: &self.annotation,
        }
    }
    pub fn as_deref(&self) -> Annotated<&T::Target, &A>
    where
        T: Deref,
    {
        self.as_ref().map(|v| v.deref())
    }
    pub fn as_deref_mut(&mut self) -> Annotated<&mut T::Target, &A>
    where
        T: DerefMut,
    {
        self.as_ref_mut().map(|v| v.deref_mut())
    }
    pub fn as_mut(&mut self) -> Annotated<&mut T, &mut A> {
        Annotated {
            value: &mut self.value,
            annotation: &mut self.annotation,
        }
    }
}
impl<T, A> Annotated<&T, &A> {
    pub fn cloned(self) -> Annotated<T, A>
    where
        T: Clone,
        A: Clone,
    {
        self.map_parts(Clone::clone, Clone::clone)
    }
}
impl<T, A> Annotated<&mut T, &A> {
    pub fn cloned(self) -> Annotated<T, A>
    where
        T: Clone,
        A: Clone,
    {
        self.map_parts(|v| v.clone(), Clone::clone)
    }
}
impl<T, A> Annotated<&T, &mut A> {
    pub fn cloned(self) -> Annotated<T, A>
    where
        T: Clone,
        A: Clone,
    {
        self.map_parts(Clone::clone, |a| a.clone())
    }
}
impl<T, A> Annotated<&mut T, &mut A> {
    pub fn cloned(self) -> Annotated<T, A>
    where
        T: Clone,
        A: Clone,
    {
        self.map_parts(|v| v.clone(), |a| a.clone())
    }
    pub fn replace(&mut self, other: Annotated<T, A>) -> Annotated<T, A> {
        Annotated {
            value: std::mem::replace(self.value, other.value),
            annotation: std::mem::replace(self.annotation, other.annotation),
        }
    }
}
impl<T, A> Annotated<&T, A> {
    pub fn value_cloned(self) -> Annotated<T, A>
    where
        T: Clone,
    {
        self.map(Clone::clone)
    }
}
impl<T, A> Annotated<&mut T, A> {
    pub fn value_cloned(self) -> Annotated<T, A>
    where
        T: Clone,
    {
        self.map(|v| v.clone())
    }
}
impl<T, A> Annotated<T, &A> {
    pub fn annotation_cloned(self) -> Annotated<T, A>
    where
        A: Clone,
    {
        self.map_annotation(Clone::clone)
    }
}
impl<T, A> Annotated<T, &mut A> {
    pub fn annotation_cloned(self) -> Annotated<T, A>
    where
        A: Clone,
    {
        self.map_annotation(|a| a.clone())
    }
}

#[cfg(test)]
pub mod tests {
    use super::*;

    #[test]
    fn test_map() {
        let one = Annotated::new(1, "first");
        let sone = one.map(|i| i.to_string());
        assert_eq!(
            sone.as_deref().annotation_cloned(),
            Annotated::new("1", "first")
        );
    }

    #[test]
    fn test_cloned() {
        let mut one = 1;
        let mut first = "first";
        let mut annotated_one = Annotated::new(1, "first");

        let one_value_ref = Annotated::new(&1, "first");
        assert_eq!(one_value_ref.value_cloned(), annotated_one);
        let one_value_ref_mut = Annotated::new(&mut one, "first");
        assert_eq!(one_value_ref_mut.value_cloned(), annotated_one);

        let one_annotation_ref = Annotated::new(1, &"first");
        assert_eq!(one_annotation_ref.annotation_cloned(), annotated_one);
        let one_annotation_ref_mut = Annotated::new(1, &mut first);
        assert_eq!(one_annotation_ref_mut.annotation_cloned(), annotated_one);

        let one_value_ref_annotation_ref = Annotated::new(&1, &"first");
        assert_eq!(one_value_ref_annotation_ref, annotated_one.as_ref());
        assert_eq!(one_value_ref_annotation_ref.cloned(), annotated_one);

        let one_value_ref_mut_annotation_ref = Annotated::new(&mut one, &first);
        assert_eq!(one_value_ref_mut_annotation_ref.cloned(), annotated_one);

        let one_value_ref_annotation_ref_mut = Annotated::new(&1, &mut first);
        assert_eq!(one_value_ref_annotation_ref_mut.cloned(), annotated_one);

        let one_value_ref_mut_annotation_ref_mut = Annotated::new(&mut one, &first);
        assert_eq!(
            one_value_ref_mut_annotation_ref_mut,
            annotated_one.as_ref_mut()
        );
        assert_eq!(one_value_ref_mut_annotation_ref_mut.cloned(), annotated_one);
    }
}
