# generate README.md:
#   cargo install cargo-rdme
#   cargo rdme install-rust-toolchain-for-intralinks
#   cargo rdme --force --intralinks-all-features

heading-base-level = 1
workspace-project = "semigroup"
