[package]
name = "semigroup_derive"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
readme.workspace = true

[lib]
proc-macro = true

[features]

[dependencies]
comfy-table = { version = "7", default-features = false }
darling = "0.23"
heck = "0.5"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
insta = "1"
prettyplease = "0.2" # rustfmt is cli only
rstest = "0.26"
